block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('app.py', '.'),
        ('knowledge_base.py', '.'),
        ('rag_qa.py', '.'),
        ('.env', '.'),
        ('docs/', 'docs/'),
        ('chroma_db/', 'chroma_db/'),
        ('.streamlit/', '.streamlit/'),
    ],
    hiddenimports=[
        'streamlit',
        'streamlit.web.cli',
        'chromadb',
        'chromadb.utils.embedding_functions',
        'langchain_text_splitters',
        'PyPDF2',
        'docx',
        'python_dotenv',
        'requests',
        'sentence_transformers',
        'transformers',
        'torch',
        'onnxruntime',
        'grpc',
        'pydantic',
        'pydantic_settings',
        'typer',
        'rich',
        'uvicorn',
        'huggingface_hub',
        'tokenizers',
        'safetensors',
        'numpy',
        'pandas',
        'scikit_learn',
        'scipy',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='RAG-QA-System',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
